[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
hex = "0.4.3"
md-5 = "0.10.6"
rs_merkle = "1.5.0"
