[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.57"
jwalk = "0.8.1"
rayon = "1.11.0"
serde = "1.0.219"
