# rustfmt.toml (stable)
max_width = 100
use_small_heuristics = "Max"

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments & strings
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
format_strings = true

# Misc
reorder_impl_items = true
newline_style = "Auto"

# ↓ These keep layout tidy
blank_lines_upper_bound = 1   # cap consecutive blank lines to 1
blank_lines_lower_bound = 0   # allow single sections without forced extra spacing
